name: climaax_floods

channels:
    - conda-forge

dependencies:
        - python=3.11
        - gdal
        - numpy
        - geopandas
        - rasterio
        - matplotlib
        - tqdm
        - pip
        - jupyterlab
        - xlrd
        - pyproj
        - xarray
        - zarr
        - rioxarray
        - osmnx
        - leafmap
        - eccodes
        - earthkit-data
        - cfgrib
        - pooch
        - scipy
        - cartopy
        - pandas
        - ipywidgets
        - ipympl
        - nbmake
        - pytest
        - contextily
        - cartopy
        - regionmask
        - planetary-computer
        - shapely
        - dask
        - distributed
        - requests
        - aiohttp
        - pip:
            - netcdf4
            - damagescanner
            - jupyterlab_myst
            - openpyxl
            - pystac-client
   
          
